# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ncc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ncc.proto',
  package='ncc',
  serialized_pb=_b('\n\tncc.proto\x12\x03ncc\"u\n\tVocabWord\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x0b\n\x03wid\x18\x02 \x01(\x05\x12\r\n\x05\x63ount\x18\x03 \x01(\x02\x12\r\n\x05slots\x18\x04 \x01(\x05\x12\x1c\n\x04kind\x18\x05 \x01(\x0e\x32\x0e.ncc.TokenKind\x12\x11\n\thypernyms\x18\x06 \x03(\t\"r\n\tDocTokEnt\x12\r\n\x05\x64ocid\x18\x01 \x01(\t\x12\x13\n\x07tok_ids\x18\x02 \x03(\x05\x42\x02\x10\x01\x12\x16\n\nent_begins\x18\x03 \x03(\x05\x42\x02\x10\x01\x12\x14\n\x08\x65nt_ends\x18\x04 \x03(\x05\x42\x02\x10\x01\x12\x13\n\x07\x65nt_ids\x18\x05 \x03(\x05\x42\x02\x10\x01\"\x87\x01\n\tTrainWork\x12\x11\n\tfocus_tid\x18\x01 \x01(\x05\x12\"\n\nfocus_kind\x18\x02 \x01(\x0e\x32\x0e.ncc.TokenKind\x12\x18\n\x0c\x63ontext_tids\x18\x03 \x03(\x05\x42\x02\x10\x01\x12)\n\rcontext_kinds\x18\x04 \x03(\x0e\x32\x0e.ncc.TokenKindB\x02\x10\x01\"`\n\x0ePhraseInstance\x12\x10\n\x08th_label\x18\x01 \x01(\t\x12\x15\n\rnoncomp_label\x18\x02 \x01(\x02\x12\x12\n\nphrase_wid\x18\x03 \x01(\x05\x12\x11\n\tword_wids\x18\x04 \x03(\x05\"\xd1\x01\n\x06\x43onfig\x12\x16\n\x08unipower\x18\x01 \x02(\x02:\x04\x30.75\x12\x10\n\x03\x64im\x18\x02 \x02(\x05:\x03\x31\x30\x30\x12\x11\n\x06window\x18\x03 \x02(\x05:\x01\x35\x12\x0e\n\x03neg\x18\x04 \x02(\x05:\x01\x35\x12\x13\n\x04step\x18\x05 \x02(\x02:\x05\x30.025\x12\x11\n\x06\x65pochs\x18\x06 \x02(\x05:\x01\x31\x12\x18\n\x05slots\x18\x07 \x02(\x05:\t100000000\x12%\n\tloss_kind\x18\x08 \x02(\x0e\x32\r.ncc.LossKind:\x03\x44ot\x12\x11\n\x05\x64\x65\x62ug\x18\xe7\x07 \x02(\x05:\x01\x30\"\x1c\n\nModelParts\x12\x0e\n\x06radius\x18\x01 \x01(\x02*K\n\tTokenKind\x12\x08\n\x04Null\x10\x00\x12\t\n\x05Token\x10\x01\x12\n\n\x06\x45ntity\x10\x02\x12\n\n\x06Phrase\x10\x03\x12\x08\n\x04Type\x10\x04\x12\x07\n\x03Hyp\x10\x05*\x1b\n\x08LossKind\x12\x07\n\x03\x44ot\x10\x01\x12\x06\n\x02L2\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TOKENKIND = _descriptor.EnumDescriptor(
  name='TokenKind',
  full_name='ncc.TokenKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Null', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Token', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Entity', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Phrase', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Type', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Hyp', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=731,
  serialized_end=806,
)
_sym_db.RegisterEnumDescriptor(_TOKENKIND)

TokenKind = enum_type_wrapper.EnumTypeWrapper(_TOKENKIND)
_LOSSKIND = _descriptor.EnumDescriptor(
  name='LossKind',
  full_name='ncc.LossKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Dot', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='L2', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=808,
  serialized_end=835,
)
_sym_db.RegisterEnumDescriptor(_LOSSKIND)

LossKind = enum_type_wrapper.EnumTypeWrapper(_LOSSKIND)
Null = 0
Token = 1
Entity = 2
Phrase = 3
Type = 4
Hyp = 5
Dot = 1
L2 = 2



_VOCABWORD = _descriptor.Descriptor(
  name='VocabWord',
  full_name='ncc.VocabWord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='ncc.VocabWord.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wid', full_name='ncc.VocabWord.wid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='ncc.VocabWord.count', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slots', full_name='ncc.VocabWord.slots', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kind', full_name='ncc.VocabWord.kind', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hypernyms', full_name='ncc.VocabWord.hypernyms', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=135,
)


_DOCTOKENT = _descriptor.Descriptor(
  name='DocTokEnt',
  full_name='ncc.DocTokEnt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='docid', full_name='ncc.DocTokEnt.docid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tok_ids', full_name='ncc.DocTokEnt.tok_ids', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='ent_begins', full_name='ncc.DocTokEnt.ent_begins', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='ent_ends', full_name='ncc.DocTokEnt.ent_ends', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='ent_ids', full_name='ncc.DocTokEnt.ent_ids', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=251,
)


_TRAINWORK = _descriptor.Descriptor(
  name='TrainWork',
  full_name='ncc.TrainWork',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='focus_tid', full_name='ncc.TrainWork.focus_tid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='focus_kind', full_name='ncc.TrainWork.focus_kind', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='context_tids', full_name='ncc.TrainWork.context_tids', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='context_kinds', full_name='ncc.TrainWork.context_kinds', index=3,
      number=4, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=389,
)


_PHRASEINSTANCE = _descriptor.Descriptor(
  name='PhraseInstance',
  full_name='ncc.PhraseInstance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='th_label', full_name='ncc.PhraseInstance.th_label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='noncomp_label', full_name='ncc.PhraseInstance.noncomp_label', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phrase_wid', full_name='ncc.PhraseInstance.phrase_wid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='word_wids', full_name='ncc.PhraseInstance.word_wids', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=487,
)


_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='ncc.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unipower', full_name='ncc.Config.unipower', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0.75,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dim', full_name='ncc.Config.dim', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='window', full_name='ncc.Config.window', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neg', full_name='ncc.Config.neg', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='step', full_name='ncc.Config.step', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0.025,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='epochs', full_name='ncc.Config.epochs', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slots', full_name='ncc.Config.slots', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=100000000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loss_kind', full_name='ncc.Config.loss_kind', index=7,
      number=8, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='debug', full_name='ncc.Config.debug', index=8,
      number=999, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=699,
)


_MODELPARTS = _descriptor.Descriptor(
  name='ModelParts',
  full_name='ncc.ModelParts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='radius', full_name='ncc.ModelParts.radius', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=701,
  serialized_end=729,
)

_VOCABWORD.fields_by_name['kind'].enum_type = _TOKENKIND
_TRAINWORK.fields_by_name['focus_kind'].enum_type = _TOKENKIND
_TRAINWORK.fields_by_name['context_kinds'].enum_type = _TOKENKIND
_CONFIG.fields_by_name['loss_kind'].enum_type = _LOSSKIND
DESCRIPTOR.message_types_by_name['VocabWord'] = _VOCABWORD
DESCRIPTOR.message_types_by_name['DocTokEnt'] = _DOCTOKENT
DESCRIPTOR.message_types_by_name['TrainWork'] = _TRAINWORK
DESCRIPTOR.message_types_by_name['PhraseInstance'] = _PHRASEINSTANCE
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
DESCRIPTOR.message_types_by_name['ModelParts'] = _MODELPARTS
DESCRIPTOR.enum_types_by_name['TokenKind'] = _TOKENKIND
DESCRIPTOR.enum_types_by_name['LossKind'] = _LOSSKIND

VocabWord = _reflection.GeneratedProtocolMessageType('VocabWord', (_message.Message,), dict(
  DESCRIPTOR = _VOCABWORD,
  __module__ = 'ncc_pb2'
  # @@protoc_insertion_point(class_scope:ncc.VocabWord)
  ))
_sym_db.RegisterMessage(VocabWord)

DocTokEnt = _reflection.GeneratedProtocolMessageType('DocTokEnt', (_message.Message,), dict(
  DESCRIPTOR = _DOCTOKENT,
  __module__ = 'ncc_pb2'
  # @@protoc_insertion_point(class_scope:ncc.DocTokEnt)
  ))
_sym_db.RegisterMessage(DocTokEnt)

TrainWork = _reflection.GeneratedProtocolMessageType('TrainWork', (_message.Message,), dict(
  DESCRIPTOR = _TRAINWORK,
  __module__ = 'ncc_pb2'
  # @@protoc_insertion_point(class_scope:ncc.TrainWork)
  ))
_sym_db.RegisterMessage(TrainWork)

PhraseInstance = _reflection.GeneratedProtocolMessageType('PhraseInstance', (_message.Message,), dict(
  DESCRIPTOR = _PHRASEINSTANCE,
  __module__ = 'ncc_pb2'
  # @@protoc_insertion_point(class_scope:ncc.PhraseInstance)
  ))
_sym_db.RegisterMessage(PhraseInstance)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(
  DESCRIPTOR = _CONFIG,
  __module__ = 'ncc_pb2'
  # @@protoc_insertion_point(class_scope:ncc.Config)
  ))
_sym_db.RegisterMessage(Config)

ModelParts = _reflection.GeneratedProtocolMessageType('ModelParts', (_message.Message,), dict(
  DESCRIPTOR = _MODELPARTS,
  __module__ = 'ncc_pb2'
  # @@protoc_insertion_point(class_scope:ncc.ModelParts)
  ))
_sym_db.RegisterMessage(ModelParts)


_DOCTOKENT.fields_by_name['tok_ids'].has_options = True
_DOCTOKENT.fields_by_name['tok_ids']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_DOCTOKENT.fields_by_name['ent_begins'].has_options = True
_DOCTOKENT.fields_by_name['ent_begins']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_DOCTOKENT.fields_by_name['ent_ends'].has_options = True
_DOCTOKENT.fields_by_name['ent_ends']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_DOCTOKENT.fields_by_name['ent_ids'].has_options = True
_DOCTOKENT.fields_by_name['ent_ids']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_TRAINWORK.fields_by_name['context_tids'].has_options = True
_TRAINWORK.fields_by_name['context_tids']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_TRAINWORK.fields_by_name['context_kinds'].has_options = True
_TRAINWORK.fields_by_name['context_kinds']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
